from datetime import datetime, timezone

from sqlalchemy import Column, String, Float, Integer, Boolean, JSON, ForeignKey, DateTime, Text
from app.db.base import Base


class AlertRule(Base):
    """Alert rule definition evaluated against metrics, logs or entity signals."""

    __tablename__ = "alert_rules"

    tenant_id = Column(String(36), ForeignKey("tenants.id"), nullable=False, index=True)
    name = Column(String(255), nullable=False)
    description = Column(Text)
    enabled = Column(Boolean, default=True)

    # Target
    entity_type = Column(String(30), default="host")
    entity_ids = Column(JSON, default=list)  # empty = all entities of type
    tags_filter = Column(JSON, default=list)

    # Condition
    metric = Column(String(100), nullable=False)
    condition_op = Column(String(10), nullable=False)   # gt|lt|gte|lte|eq|ne
    threshold_value = Column(Float, nullable=False)
    duration_seconds = Column(Integer, default=60)

    # Use AI baseline instead of fixed threshold
    use_baseline = Column(Boolean, default=False)
    baseline_sensitivity = Column(Float, default=3.0)  # sigma deviation

    severity = Column(String(20), default="medium")
    channels = Column(JSON, default=list)  # channel IDs
    suppress_seconds = Column(Integer, default=300)   # cooldown
    created_by = Column(String(36), ForeignKey("users.id"))


class Alert(Base):
    """Alert or incident generated by a rule, anomaly baseline or security signal."""

    __tablename__ = "alerts"

    def __init__(self, **kwargs):
        title = kwargs.pop("title", None)
        resource = kwargs.pop("resource", None)
        resolved = kwargs.pop("resolved", None)
        super().__init__(**kwargs)
        if title is not None and not self.name:
            self.name = title
        if resource is not None and not self.entity_name:
            self.entity_name = resource
        if not self.name:
            self.name = "Alert"
        if not self.triggered_at:
            self.triggered_at = datetime.now(timezone.utc)
        if resolved is not None:
            self.resolved = resolved

    tenant_id = Column(String(36), ForeignKey("tenants.id"), nullable=False, index=True)
    rule_id = Column(String(36), ForeignKey("alert_rules.id"), nullable=True)
    anomaly_id = Column(String(36), ForeignKey("anomaly_events.id"), nullable=True)

    name = Column(String(255), nullable=False)
    description = Column(Text)
    severity = Column(String(20), default="medium")  # critical|high|medium|low|info

    entity_type = Column(String(30))
    entity_id = Column(String(36), index=True)
    entity_name = Column(String(255))

    metric = Column(String(100))
    observed_value = Column(Float)
    threshold_value = Column(Float)
    condition_op = Column(String(10))

    status = Column(String(20), default="active")  # active|acknowledged|resolved
    triggered_at = Column(DateTime(timezone=True), nullable=False, index=True, default=lambda: datetime.now(timezone.utc))
    acknowledged_at = Column(DateTime(timezone=True))
    resolved_at = Column(DateTime(timezone=True))
    acknowledged_by = Column(String(36), ForeignKey("users.id"))
    trigger_count = Column(Integer, default=1)

    # AI analysis (from anomaly or auto-generated)
    ai_summary = Column(Text)
    ai_root_cause = Column(Text)
    ai_recommendation = Column(Text)

    # Notification tracking
    notifications_sent = Column(JSON, default=list)

    @property
    def title(self) -> str:
        """Compatibility alias for alert name."""
        return self.name

    @title.setter
    def title(self, value: str) -> None:
        self.name = value

    @property
    def resource(self) -> str | None:
        """Compatibility alias for the affected entity name."""
        return self.entity_name

    @resource.setter
    def resource(self, value: str | None) -> None:
        self.entity_name = value

    @property
    def resolved(self) -> bool:
        """Compatibility boolean derived from alert status."""
        return self.status == "resolved"

    @resolved.setter
    def resolved(self, value: bool) -> None:
        self.status = "resolved" if value else "active"
