apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "las.fullname" . }}-beat
  namespace: {{ include "las.namespace" . }}
  labels:
    {{- include "las.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas.beat }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "las.name" . }}
      app.kubernetes.io/component: beat
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "las.labels" . | nindent 8 }}
        app.kubernetes.io/component: beat
    spec:
      serviceAccountName: {{ include "las.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      containers:
        - name: beat
          image: "{{ .Values.images.api.repository }}:{{ .Values.images.api.tag }}"
          imagePullPolicy: {{ .Values.images.api.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - python -m celery -A app.workers.celery_app.celery_app beat -l info
          envFrom:
            - secretRef:
                name: {{ include "las.fullname" . }}-env
          resources:
            {{- toYaml .Values.resources.beat | nindent 12 }}
