{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "las.fullname" . }}-postgres
  namespace: {{ include "las.namespace" . }}
  labels:
    {{- include "las.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "las.name" . }}
    app.kubernetes.io/component: postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
{{- end }}
