{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "las.serviceAccountName" . }}
  namespace: {{ include "las.namespace" . }}
  labels:
    {{- include "las.labels" . | nindent 4 }}
{{- end }}
